### ISSUE TITLE
Convert '1993-1995' into single year

### ISSUE THREAD

**Issue by anuveyatsu** [datasets/london-life-expectancy#1]
See `Year` column in https://github.com/datasets/london-life-expectancy/blob/master/data/female-life-expectancy.csv - you notice that its format is `1993-1995` but we want, e.g., `1995`. It might not be as accurate as original one but we need it to make easy to visualize.

## Tasks

* [x] convert https://github.com/datasets/london-life-expectancy/blob/master/data/female-life-expectancy.csv
* [x] convert https://github.com/datasets/london-life-expectancy/blob/master/data/male-life-expectancy.csv
* [x] publish under `london` user on datahub
